### ISSUE TITLE
Another API change

### ISSUE THREAD

**Issue by VibroAxe** [Matthew1471/MyEE-API#2]
Looks like EE have changed something in the logon again. :'(

```
/usr/bin/python3 MyEEDataGift.py
* Logging into My EE.
Traceback (most recent call last):
  File "MyEEDataGift.py", line 34, in <module>
    myEE = MyEE(credentials['MyEE_Username'], credentials['MyEE_Password'])
  File "/storage/home/vibs/git/MyEE-API/shared/myee.py", line 52, in __init__
    if not self.login(settingsJSON, email, password):
  File "/storage/home/vibs/git/MyEE-API/shared/myee.py", line 169, in login
    if not self.QueueITToken:
AttributeError: 'MyEE' object has no attribute 'QueueITToken'
```

**Comment by Matthew1471** [comment]
So they have, try 54d46d6 :)

I kind of like the new changes - they've removed some of the crud that should never have been in there in the first place (the queue was supposed to be for the shop during iPhone launches - didn't make any sense to make customers queue to get into their accounts to pay their bills etc). Also they're moving away from myaccount.ee.co.uk and dumping it on ee.co.uk/ itself.. although there are some remenants of myaccount.ee.co.uk still, EE just couldn't resist adding another HTTP redirect :-)

I haven't extensively tested this as I don't need to datagift, but login is succeeding and I was able to switch accounts and pull my dataPassHistory, so on paper this should all work for you too.

**Comment by VibroAxe** [comment]
Sorry I've been on Greece so hadn't had the time to try it! Just tried and all works. Thanks for the hard work as always
